# Generated by Django 3.1.2 on 2020-10-20 05:38

import apps.payments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='currency of stripe')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description of currency')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name of product')),
                ('description', models.TextField(verbose_name='description of product')),
                ('stripe_id', models.TextField(blank=True, null=True, verbose_name='id of stripe')),
                ('active', models.BooleanField(default=True, verbose_name='product active')),
                ('photo', models.ImageField(upload_to=apps.payments.models.path_and_rename, verbose_name='image product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='amount of plan')),
                ('stripe_id', models.TextField(blank=True, null=True, verbose_name='id of stripe')),
                ('nickname', models.CharField(max_length=200, verbose_name='name of product')),
                ('interval', models.PositiveSmallIntegerField(choices=[(1, 'month'), (2, 'year')], default=1, verbose_name='Charges interval plan money')),
                ('active', models.BooleanField(default=True, verbose_name='product active')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.product', verbose_name='Product relation')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
    ]
