# Generated by Django 3.1.2 on 2020-10-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='product',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
