# Generated by Django 3.1.2 on 2020-10-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20201022_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='has_renewable',
            field=models.BooleanField(default=False, verbose_name='active subscription'),
        ),
    ]
