# Generated by Django 3.1.2 on 2020-10-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20201022_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='has_renewable',
            field=models.BooleanField(default=False, verbose_name='renewable subscription'),
        ),
    ]
