# Generated by Django 3.1.2 on 2020-10-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20201022_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='fee_stripe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='fee of stripe of subscription in dollars'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='tax payed of subscription in dollars'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='total payed of subscription in dollars'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='total_team',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='number of coaches'),
            preserve_default=False,
        ),
    ]
