# Generated by Django 3.1.2 on 2020-10-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20201022_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='total_team',
            field=models.PositiveSmallIntegerField(verbose_name='number of teams'),
        ),
    ]
