# Generated by Django 3.1.2 on 2021-04-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushInformation',
        ),
    ]
