# Generated by Django 3.1.2 on 2020-10-15 16:14

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', timezone_field.fields.TimeZoneField(default='America/Merida')),
                ('name', models.CharField(max_length=50, verbose_name='Title region')),
            ],
        ),
    ]
