# Generated by Django 3.1.2 on 2020-10-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20201015_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='timezone',
        ),
        migrations.AddField(
            model_name='region',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'EUR'), (2, 'USD'), (3, 'MXN')], default=3, verbose_name='currency user'),
        ),
    ]
