# Generated by Django 3.1.2 on 2021-02-19 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0059_auto_20210204_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockNivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_exercise', models.CharField(max_length=50, verbose_name='Type name')),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.blocktype', verbose_name='BlockType nivel')),
            ],
            options={
                'verbose_name': 'Block nivel',
                'verbose_name_plural': 'Block nivels',
            },
        ),
        migrations.CreateModel(
            name='CategorySelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Selection name')),
                ('quantity_exercise', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.blocknivel', verbose_name='Related block_nivel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_selection_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='created_by category_selection')),
            ],
            options={
                'verbose_name': 'Category selection',
                'verbose_name_plural': 'Categories selection',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nivel name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_trainings', models.IntegerField(blank=True, null=True, verbose_name='quantity trainings')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nivel_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='updated_by nivel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Related Users')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Nivels',
            },
        ),
        migrations.CreateModel(
            name='WorkoutNivelPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.DateTimeField(max_length=100, verbose_name='Phase training')),
                ('accomplished', models.BooleanField(default=True, verbose_name='Realized WorkOut')),
                ('workout', models.TextField(blank=True, default='{}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_user', to='coach.nivel', verbose_name='Related Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='SetsReps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps_light_equip', models.CharField(blank=True, max_length=30, null=True, verbose_name='reps light equipment')),
                ('reps_heavy_equip', models.CharField(blank=True, max_length=30, null=True, verbose_name='reps heavy equipment')),
                ('reps_lower_body_without_equipment', models.CharField(blank=True, max_length=30, null=True, verbose_name='reps lower body')),
                ('reps_upper_body_without_equipment', models.CharField(blank=True, max_length=30, null=True, verbose_name='reps upper body')),
                ('intensity_equipment_RM', models.IntegerField(blank=True, null=True, verbose_name='intensity')),
                ('seconds_exercise', models.IntegerField(blank=True, null=True, verbose_name='rest exercise')),
                ('rest_exercise', models.IntegerField(blank=True, null=True, verbose_name='rest exercise')),
                ('rir', models.IntegerField(blank=True, null=True, verbose_name='RIR')),
                ('reps_vertical_jump', models.IntegerField(blank=True, null=True, verbose_name='reps vertical jump')),
                ('reps_explosive', models.IntegerField(blank=True, null=True, verbose_name='reps explosive')),
                ('increment_load_week', models.IntegerField(blank=True, null=True, verbose_name='increment load week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_nivel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coach.blocknivel', verbose_name='Block nivel setsreps')),
                ('category_selection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coach.categoryselection', verbose_name='Category_selection setsreps')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setsreps_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='created_by setsreps')),
                ('nivel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coach.nivel', verbose_name='Nivel setsreps')),
                ('subparam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setsreps_subparameter', to='catalog.blockexercisecatalogsubparameter', verbose_name='Related Subparameter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setsreps_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='updated_by setsreps')),
            ],
            options={
                'verbose_name_plural': 'Sets and Reps',
            },
        ),
        migrations.CreateModel(
            name='HierarchyRegions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name Regiom')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='catalog.subcategory', verbose_name='Name Regions')),
            ],
        ),
        migrations.AddField(
            model_name='categoryselection',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.nivel', verbose_name='type nivel'),
        ),
        migrations.AddField(
            model_name='categoryselection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_selection_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='updated_by category_selection'),
        ),
        migrations.AddField(
            model_name='blocknivel',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.nivel', verbose_name='Related Nivel'),
        ),
    ]
