# Generated by Django 3.1.2 on 2021-02-23 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0069_exercise_identifier'),
        ('coach', '0002_auto_20210222_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hierarchyregions',
            options={'verbose_name': 'Hierarchy Region', 'verbose_name_plural': 'Hierarchy Regions'},
        ),
        migrations.RemoveField(
            model_name='blocknivel',
            name='block_type',
        ),
        migrations.RemoveField(
            model_name='blocknivel',
            name='type_exercise',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='quantity_trainings',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='setsreps',
            name='category_selection',
        ),
        migrations.RemoveField(
            model_name='setsreps',
            name='nivel',
        ),
        migrations.AddField(
            model_name='nivel',
            name='number_initial',
            field=models.IntegerField(default=None, verbose_name='First number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel',
            name='number_next_level',
            field=models.IntegerField(default=None, verbose_name='Quantity next level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blocknivel',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.nivel', verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='setsreps',
            name='block_nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_nivel_setsreps', to='coach.blocknivel', verbose_name='Block Nivel setsreps'),
        ),
        migrations.AlterField(
            model_name='setsreps',
            name='seconds_exercise',
            field=models.IntegerField(blank=True, null=True, verbose_name='seconds_exercise'),
        ),
        migrations.AlterField(
            model_name='workoutnivelphase',
            name='phase',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workoutnivelphase',
            name='workout',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NivelUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_trainings', models.IntegerField(blank=True, null=True, verbose_name='quantity trainings')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach.nivel', verbose_name='Related Nivel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nivel_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='updated_by nivel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Related Users')),
            ],
            options={
                'verbose_name': 'Nivel User',
                'verbose_name_plural': 'Nivel Users',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_exercise', models.CharField(max_length=50, verbose_name='Type name')),
                ('catalog_block_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_block_type', to='catalog.blocktype', verbose_name='BlockType nivel')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
            },
        ),
        migrations.AddField(
            model_name='blocknivel',
            name='block',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coach.block', verbose_name='block'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutnivelphase',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_user', to='coach.niveluser', verbose_name='Related Nivel'),
        ),
    ]
