# Generated by Django 3.1.2 on 2021-02-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_auto_20210223_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setsreps',
            name='seconds_exercise',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='seconds_exercise'),
        ),
    ]
