# Generated by Django 3.1.2 on 2021-02-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_auto_20210223_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setsreps',
            name='rest_exercise',
            field=models.FloatField(blank=True, null=True, verbose_name='rest exercise'),
        ),
    ]
