# Generated by Django 3.1.2 on 2021-02-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_auto_20210223_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setsreps',
            name='reps_heavy_equip',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='reps heavy equipment'),
        ),
        migrations.AlterField(
            model_name='setsreps',
            name='reps_light_equip',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='reps light equipment'),
        ),
        migrations.AlterField(
            model_name='setsreps',
            name='reps_lower_body_without_equipment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='reps lower body'),
        ),
        migrations.AlterField(
            model_name='setsreps',
            name='reps_upper_body_without_equipment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='reps upper body'),
        ),
    ]
