# Generated by Django 3.1.2 on 2021-02-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_auto_20210224_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryselectionniveluser',
            name='category_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_nivel_user', to='coach.category', verbose_name='Related category_selection'),
        ),
    ]
