# Generated by Django 3.1.2 on 2021-03-18 21:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coach', '0010_categoryselectionniveluser_equip'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='niveluser',
            unique_together={('user',)},
        ),
    ]
