# Generated by Django 3.1.2 on 2021-03-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0011_auto_20210318_1513'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='niveluser',
            unique_together=set(),
        ),
    ]
