# Generated by Django 3.1.2 on 2021-03-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0012_auto_20210318_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryselectionniveluser',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active category'),
        ),
    ]
