# Generated by Django 3.1.2 on 2021-03-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0013_categoryselectionniveluser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='description',
            field=models.CharField(blank=True, default='description', max_length=500, null=True, verbose_name='Description'),
        ),
    ]
