# Generated by Django 3.1.2 on 2021-03-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0015_auto_20210329_1644'),
        ('coach', '0015_auto_20210330_0359'),
    ]

    operations = [
    ]
