# Generated by Django 3.1.2 on 2021-03-31 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0083_auto_20210329_1656'),
        ('coach', '0016_auto_20210331_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipuser',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipuser',
            name='equipment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='equip_user', to='catalog.subcategory', verbose_name='Equipment'),
            preserve_default=False,
        ),
    ]
