# Generated by Django 3.1.2 on 2021-03-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0016_merge_20210330_1143'),
        ('coach', '0017_auto_20210331_0538'),
    ]

    operations = [
    ]
