# Generated by Django 3.1.2 on 2021-04-05 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0083_auto_20210329_1656'),
        ('coach', '0018_merge_20210331_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipuser',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipuser',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='equip_user', to='catalog.SubCategory', verbose_name='Equipment'),
        ),
        migrations.AlterField(
            model_name='hierarchyregions',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='catalog.subcategory', verbose_name='Name Regions'),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='description',
            field=models.CharField(default='Description', max_length=500, verbose_name='Description'),
        ),
    ]
