# Generated by Django 3.1.2 on 2020-11-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20201105_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='code',
            field=models.CharField(default='test', max_length=50, verbose_name='Subcategory name'),
            preserve_default=False,
        ),
    ]
