# Generated by Django 3.1.2 on 2020-11-06 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20201105_1820'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_auto_20201105_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_updated_by', to='teams.institution', verbose_name='Institution excercice'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='has_library',
            field=models.BooleanField(default=False, verbose_name='subcategory active'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Last updated'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='request_library',
            field=models.BooleanField(default=False, verbose_name='subcategory active'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='url_file',
            field=models.TextField(blank=True, null=True, verbose_name='Url video'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='url_thumb',
            field=models.TextField(blank=True, null=True, verbose_name='Url thumbnail'),
        ),
    ]
