# Generated by Django 3.1.2 on 2020-11-06 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201106_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='institution',
        ),
    ]
