# Generated by Django 3.1.2 on 2020-11-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201106_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='note',
            field=models.TextField(default='testW', verbose_name='Note of excercice'),
            preserve_default=False,
        ),
    ]
