# Generated by Django 3.1.2 on 2020-11-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_exercise_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='has_library',
            field=models.BooleanField(default=False, verbose_name='library active'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='request_library',
            field=models.BooleanField(default=False, verbose_name='request active'),
        ),
    ]
