# Generated by Django 3.1.2 on 2020-11-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201106_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default='code', max_length=150, unique=True, verbose_name='Code category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
    ]
