# Generated by Django 3.1.2 on 2020-11-18 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0013_auto_20201105_1820'),
        ('catalog', '0010_auto_20201107_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Program name')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Order of program')),
                ('active', models.BooleanField(default=True, verbose_name='Program active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athletes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Assigned athletes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Institution program')),
                ('teams', models.ManyToManyField(blank=True, to='teams.Team', verbose_name='Assigned teams')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Institution program')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Phase name')),
                ('active', models.BooleanField(default=True, verbose_name='Phase active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Institution phase')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_phase', to='catalog.program', verbose_name='Program phase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Institution phase')),
            ],
            options={
                'verbose_name': 'Phase',
                'verbose_name_plural': 'Phases',
            },
        ),
    ]
