# Generated by Django 3.1.2 on 2020-11-20 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0012_auto_20201120_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Week name')),
                ('volumen', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(verbose_name='Order of week')),
                ('active', models.BooleanField(default=True, verbose_name='Week active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='week_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Institution week')),
                ('phase', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phase_week', to='catalog.phase', verbose_name='Phase week')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='week_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Institution week')),
            ],
            options={
                'verbose_name': 'Week',
                'verbose_name_plural': 'Weeks',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUES', 'Tuesday'), ('WED', 'Wednesday'), ('THURS', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], default='SUN', max_length=250, verbose_name='Day name')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Week day')),
                ('active', models.BooleanField(default=True, verbose_name='Day active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Institution day')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Institution day')),
                ('week', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_day', to='catalog.week', verbose_name='Week day')),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
                'unique_together': {('day', 'week')},
            },
        ),
    ]
