# Generated by Django 3.1.2 on 2020-11-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_block_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='level_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_many_level', to='catalog.Category', verbose_name='Category many level'),
        ),
    ]
