# Generated by Django 3.1.2 on 2020-11-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_subcategory_level_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note of excercice'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sub_category',
            field=models.ManyToManyField(blank=True, to='catalog.SubCategory', verbose_name='Subcategories Exercise'),
        ),
    ]
