# Generated by Django 3.1.2 on 2020-11-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20201123_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='level_category',
            field=models.ManyToManyField(blank=True, related_name='category_many_level', to='catalog.Category', verbose_name='Category many level'),
        ),
    ]
