# Generated by Django 3.1.2 on 2020-11-26 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0017_auto_20201124_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Type name')),
                ('active', models.BooleanField(default=True, verbose_name='Type active')),
            ],
            options={
                'verbose_name': 'Block type',
                'verbose_name_plural': 'Block types',
            },
        ),
        migrations.RemoveField(
            model_name='block',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='block',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='block',
            name='has_library',
            field=models.BooleanField(default=False, verbose_name='library active'),
        ),
        migrations.AddField(
            model_name='block',
            name='mins',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. of mins'),
        ),
        migrations.AddField(
            model_name='block',
            name='request_library',
            field=models.BooleanField(default=False, verbose_name='request active'),
        ),
        migrations.AddField(
            model_name='block',
            name='rounds',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='No. of rounds'),
        ),
        migrations.AddField(
            model_name='day',
            name='has_library',
            field=models.BooleanField(default=False, verbose_name='library active'),
        ),
        migrations.AddField(
            model_name='day',
            name='request_library',
            field=models.BooleanField(default=False, verbose_name='request active'),
        ),
        migrations.AddField(
            model_name='phase',
            name='has_library',
            field=models.BooleanField(default=False, verbose_name='library active'),
        ),
        migrations.AddField(
            model_name='phase',
            name='request_library',
            field=models.BooleanField(default=False, verbose_name='request active'),
        ),
        migrations.AddField(
            model_name='program',
            name='has_library',
            field=models.BooleanField(default=False, verbose_name='library active'),
        ),
        migrations.AddField(
            model_name='program',
            name='request_library',
            field=models.BooleanField(default=False, verbose_name='request active'),
        ),
        migrations.AddField(
            model_name='week',
            name='has_library',
            field=models.BooleanField(default=False, verbose_name='library active'),
        ),
        migrations.AddField(
            model_name='week',
            name='request_library',
            field=models.BooleanField(default=False, verbose_name='request active'),
        ),
        migrations.AddField(
            model_name='workout',
            name='has_library',
            field=models.BooleanField(default=False, verbose_name='library active'),
        ),
        migrations.AddField(
            model_name='workout',
            name='request_library',
            field=models.BooleanField(default=False, verbose_name='request active'),
        ),
        migrations.AlterField(
            model_name='block',
            name='limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Limit of exercises in a block'),
        ),
        migrations.CreateModel(
            name='ExerciseBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveSmallIntegerField(verbose_name='No. of reps')),
                ('active', models.BooleanField(default=True, verbose_name='Exercise block active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_library', models.BooleanField(default=False, verbose_name='library active')),
                ('request_library', models.BooleanField(default=False, verbose_name='request active')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='catalog.block', verbose_name='Block exercise')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exerciseblock_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Institution exercise block')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.exercise', verbose_name='Exercise')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exerciseblock_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Institution exercise block')),
            ],
            options={
                'verbose_name': 'Exercise block',
                'verbose_name_plural': 'Exercise blocks',
            },
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.blocktype', verbose_name='Type block'),
        ),
    ]
