# Generated by Django 3.1.2 on 2020-12-01 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_coding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name category')),
                ('coding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.coding', verbose_name='item subcategory of category')),
            ],
            options={
                'verbose_name': 'Coding Category',
                'verbose_name_plural': 'Coding Categories',
            },
        ),
    ]
