# Generated by Django 3.1.2 on 2020-12-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_codingcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='category',
        ),
        migrations.AddField(
            model_name='block',
            name='coding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.coding', verbose_name='Coding block'),
        ),
        migrations.AddField(
            model_name='block',
            name='sub_coding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.codingcategory', verbose_name='Coding category block'),
        ),
        migrations.AlterField(
            model_name='block',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_workout', to='catalog.workout', verbose_name='Block workout'),
        ),
    ]
