# Generated by Django 3.1.2 on 2020-12-01 23:55

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20201201_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coding',
            name='icon',
            field=models.FileField(upload_to=apps.catalog.models.path_and_rename_icon, verbose_name='icon category'),
        ),
    ]
