# Generated by Django 3.1.2 on 2020-12-02 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0024_auto_20201202_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='order',
        ),
        migrations.RemoveField(
            model_name='program',
            name='request_library',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='program',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='created_by program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='updated_by program'),
        ),
    ]
