# Generated by Django 3.1.2 on 2020-12-02 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20201105_1820'),
        ('catalog', '0025_auto_20201202_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='athletes',
        ),
        migrations.AlterField(
            model_name='program',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Assigned team'),
        ),
    ]
