# Generated by Django 3.1.2 on 2020-12-02 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0026_auto_20201202_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='request_library',
        ),
        migrations.AlterField(
            model_name='phase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='created_by phase'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='updated_by phase'),
        ),
    ]
