# Generated by Django 3.1.2 on 2020-12-02 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0027_auto_20201202_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='request_library',
        ),
        migrations.AlterField(
            model_name='week',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='week_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='created_by week'),
        ),
        migrations.AlterField(
            model_name='week',
            name='has_library',
            field=models.BooleanField(default=False, verbose_name='has_library'),
        ),
        migrations.AlterField(
            model_name='week',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='week_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='updated_by week'),
        ),
    ]
