# Generated by Django 3.1.2 on 2020-12-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20201202_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='ends',
            field=models.DateField(default='2020-11-12', verbose_name='week ends'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='starts',
            field=models.DateField(default='2020-11-12', verbose_name='week starts'),
            preserve_default=False,
        ),
    ]
