# Generated by Django 3.1.2 on 2020-12-02 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0030_auto_20201202_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='request_library',
        ),
        migrations.AlterField(
            model_name='workout',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='created_by workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='updated_by workout'),
        ),
    ]
