# Generated by Django 3.1.2 on 2020-12-02 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0031_auto_20201202_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='request_library',
        ),
        migrations.AlterField(
            model_name='block',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='created_by block'),
        ),
        migrations.AlterField(
            model_name='block',
            name='sub_coding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.codingcategory', verbose_name='sub_coding category block'),
        ),
        migrations.AlterField(
            model_name='block',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='updated_by block'),
        ),
    ]
