# Generated by Django 3.1.2 on 2020-12-04 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0034_auto_20201203_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='atlhetes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Assigned athletes'),
        ),
    ]
