# Generated by Django 3.1.2 on 2020-12-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_program_atlhetes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='active',
        ),
        migrations.RemoveField(
            model_name='day',
            name='has_library',
        ),
    ]
