# Generated by Django 3.1.2 on 2020-12-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_auto_20201207_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='atlhetes',
            new_name='athletes',
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Program name'),
        ),
    ]
