# Generated by Django 3.1.2 on 2020-12-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0040_auto_20201209_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order of phase'),
        ),
    ]
