# Generated by Django 3.1.2 on 2021-01-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_phase_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='url_file',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='url_thumb',
        ),
        migrations.CreateModel(
            name='MediaExercice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(verbose_name='Path s3 Exercice')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.exercise', verbose_name='Related Exercice')),
            ],
            options={
                'verbose_name': 'Media Exercice',
                'verbose_name_plural': 'Media Exercices',
            },
        ),
        migrations.CreateModel(
            name='GiftExercice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(verbose_name='Path s3 Exercice')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.exercise', verbose_name='Related Exercice')),
            ],
            options={
                'verbose_name': 'Gift Exercice',
                'verbose_name_plural': 'Gift Exercices',
            },
        ),
    ]
