# Generated by Django 3.1.2 on 2021-01-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_auto_20210107_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaexercice',
            name='thumbnail',
            field=models.TextField(blank=True, null=True, verbose_name='Path s3 Exercice'),
        ),
    ]
