# Generated by Django 3.1.2 on 2021-01-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_mediaexercice_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaexercice',
            name='thumbnail',
            field=models.TextField(blank=True, null=True, verbose_name='Path s3 thumbnail Exercice'),
        ),
    ]
