# Generated by Django 3.1.2 on 2021-01-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_auto_20210108_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='has_library',
            field=models.BooleanField(default=False, verbose_name='has library'),
        ),
    ]
