# Generated by Django 3.1.2 on 2021-01-13 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0013_auto_20201105_1820'),
        ('catalog', '0045_auto_20210111_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseblock',
            name='intitution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.institution', verbose_name='Institution exercise block'),
        ),
        migrations.AlterField(
            model_name='exerciseblock',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exerciseblock_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='user created exercise block'),
        ),
        migrations.AlterField(
            model_name='exerciseblock',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exerciseblock_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='user update exercise block'),
        ),
    ]
