# Generated by Django 3.1.2 on 2021-01-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_auto_20210113_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseblock',
            old_name='intitution',
            new_name='institution',
        ),
    ]
