# Generated by Django 3.1.2 on 2021-01-18 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_auto_20210113_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='category active')),
            ],
            options={
                'verbose_name': 'Category Level',
                'verbose_name_plural': 'Categories Level',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='category_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.categorylevel'),
        ),
    ]
