# Generated by Django 3.1.2 on 2021-01-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_auto_20210118_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=150, verbose_name='Code category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('code', 'category_level')},
        ),
    ]
