# Generated by Django 3.1.2 on 2021-01-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_auto_20210118_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockExerciseCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Block Exercise Catalog',
                'verbose_name_plural': 'Block Exercise Catalogs',
            },
        ),
        migrations.AddField(
            model_name='exerciseblock',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
