# Generated by Django 3.1.2 on 2021-01-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_auto_20210125_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceBlockExerciseCatalogSubparameter',
        ),
    ]
