# Generated by Django 3.1.2 on 2021-01-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_delete_choiceblockexercisecatalogsubparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockexercisecatalog',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
