# Generated by Django 3.1.2 on 2021-01-25 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0054_blockexercisecatalog_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseBlockRelatedCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_exercise_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.blockexercisecatalog')),
                ('exercise_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.exerciseblock')),
            ],
            options={
                'verbose_name': 'Exercise Block Related Catalog',
                'verbose_name_plural': 'Exercise Block Related Catalogs',
                'unique_together': {('exercise_block', 'block_exercise_catalog')},
            },
        ),
    ]
