# Generated by Django 3.1.2 on 2021-01-27 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_exerciseblockrelatedcatalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockexercisecatalog',
            options={'ordering': ('-id',), 'verbose_name': 'Block Exercise Catalog', 'verbose_name_plural': 'Block Exercise Catalogs'},
        ),
        migrations.AlterModelOptions(
            name='exerciseblockrelatedcatalog',
            options={'ordering': ('block_exercise_catalog__id',), 'verbose_name': 'Exercise Block Related Catalog', 'verbose_name_plural': 'Exercise Block Related Catalogs'},
        ),
        migrations.AlterField(
            model_name='blockexercisecatalogsubparameter',
            name='type',
            field=models.IntegerField(choices=[(1, 'Numeric'), (2, 'Numeric Catalogs'), (7, 'Percentage Catalogs'), (3, 'Time'), (4, 'Choice'), (5, 'Percentaje'), (6, 'Character of effort')], default=1, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='ItemExerciseBlockRelatedCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('value1', models.CharField(max_length=250)),
                ('value2', models.CharField(max_length=250)),
                ('value_extra', models.CharField(max_length=250)),
                ('has_range', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'Numeric'), (2, 'Numeric Catalogs'), (7, 'Percentage Catalogs'), (3, 'Time'), (4, 'Choice'), (5, 'Percentaje'), (6, 'Character of effort')], default=1, verbose_name='type')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.exerciseblockrelatedcatalog')),
            ],
            options={
                'verbose_name': 'Item Exercise Block Related Catalog',
                'verbose_name_plural': 'Items Exercise Block Related Catalog',
                'ordering': ('row',),
                'unique_together': {('catalog', 'row')},
            },
        ),
    ]
