# Generated by Django 3.1.2 on 2021-01-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0056_auto_20210126_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemexerciseblockrelatedcatalog',
            name='value2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='itemexerciseblockrelatedcatalog',
            name='value_extra',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
