# Generated by Django 3.1.2 on 2021-01-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0057_auto_20210126_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockexercisecatalog',
            name='visible',
        ),
        migrations.AddField(
            model_name='blockexercisecatalog',
            name='has_rest',
            field=models.BooleanField(default=False),
        ),
    ]
