# Generated by Django 3.1.2 on 2021-02-04 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0058_auto_20210127_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5, verbose_name='title conversion')),
            ],
            options={
                'verbose_name': 'Conversion Measure',
                'verbose_name_plural': 'Conversion Measures',
            },
        ),
        migrations.RemoveField(
            model_name='itemexerciseblockrelatedcatalog',
            name='type',
        ),
        migrations.AddField(
            model_name='itemexerciseblockrelatedcatalog',
            name='catalog_subparameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.blockexercisecatalogsubparameter'),
        ),
        migrations.AddField(
            model_name='itemexerciseblockrelatedcatalog',
            name='conversion',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='type conversion'),
        ),
        migrations.AlterField(
            model_name='exerciseblock',
            name='has_library',
            field=models.BooleanField(default=False, verbose_name='has library'),
        ),
        migrations.AddField(
            model_name='blockexercisecatalogsubparameter',
            name='conversion_measure',
            field=models.ManyToManyField(blank=True, to='catalog.ConversionMeasure'),
        ),
    ]
