# Generated by Django 3.1.2 on 2021-02-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0060_auto_20210204_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockexercisecatalogsubparameter',
            name='measure',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Measure'),
        ),
    ]
