# Generated by Django 3.1.2 on 2021-02-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0061_blockexercisecatalogsubparameter_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockexercisecatalogsubparameter',
            name='order',
            field=models.IntegerField(default=1, verbose_name='ordering'),
        ),
    ]
