# Generated by Django 3.1.2 on 2021-02-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0062_blockexercisecatalogsubparameter_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockexercisecatalogsubparameter',
            options={'ordering': ['type'], 'verbose_name': 'Block Exercise Catalog Subparameter', 'verbose_name_plural': 'Block Exercise Catalog Subparameters'},
        ),
        migrations.AlterField(
            model_name='week',
            name='ends',
            field=models.DateField(blank=True, null=True, verbose_name='week ends'),
        ),
        migrations.AlterField(
            model_name='week',
            name='starts',
            field=models.DateField(blank=True, null=True, verbose_name='week starts'),
        ),
    ]
