# Generated by Django 3.1.2 on 2021-02-12 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0064_auto_20210209_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='created_by workout'),
        ),
        migrations.AddField(
            model_name='workout',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='updated_by workout'),
        ),
    ]
