# Generated by Django 3.1.2 on 2021-02-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20201105_1820'),
        ('catalog', '0065_auto_20210212_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.institution', verbose_name='institution created'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Workout location'),
        ),
    ]
