# Generated by Django 3.1.2 on 2021-02-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0066_auto_20210216_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemexerciseblockrelatedcatalog',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Warm Up'), (2, 'Failure'), (3, 'Drops set')], default=1, verbose_name='type'),
        ),
    ]
