# Generated by Django 3.1.2 on 2021-03-03 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0070_auto_20210225_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseblock',
            name='code',
            field=models.CharField(default='A1', max_length=3, verbose_name='Code block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseblock',
            name='superset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exerciseblock_superset', to='catalog.exerciseblock', verbose_name='Superset Exersice'),
        ),
    ]
