# Generated by Django 3.1.2 on 2021-03-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0071_auto_20210303_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseblock',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Code block'),
        ),
    ]
