# Generated by Django 3.1.2 on 2021-03-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20201105_1820'),
        ('catalog', '0073_auto_20210304_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='team',
        ),
        migrations.AddField(
            model_name='program',
            name='teams',
            field=models.ManyToManyField(blank=True, to='teams.Team', verbose_name='Assigned teams'),
        ),
    ]
