# Generated by Django 3.1.2 on 2021-03-11 01:09

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0074_auto_20210308_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockexercisecatalog',
            options={'ordering': ('order',), 'verbose_name': 'Block Exercise Catalog', 'verbose_name_plural': 'Block Exercise Catalogs'},
        ),
        migrations.AddField(
            model_name='blockexercisecatalog',
            name='icon_off',
            field=models.FileField(blank=True, null=True, upload_to=apps.catalog.models.path_and_rename_icon_exercie, verbose_name='icon category'),
        ),
        migrations.AddField(
            model_name='blockexercisecatalog',
            name='icon_on',
            field=models.FileField(blank=True, null=True, upload_to=apps.catalog.models.path_and_rename_icon_exercie, verbose_name='icon category'),
        ),
        migrations.AddField(
            model_name='blockexercisecatalog',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
    ]
