# Generated by Django 3.1.2 on 2021-03-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0075_auto_20210310_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowblocktype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Warm Up'), (2, 'Failure'), (3, 'Drops set'), (4, 'Default')], default=1, verbose_name='type'),
        ),
    ]
