# Generated by Django 3.1.2 on 2021-03-22 06:50

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0076_auto_20210317_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.catalog.models.path_and_rename_equipment, verbose_name='Image Equipment'),
        ),
        migrations.CreateModel(
            name='CategoryEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name Category')),
                ('equipment', models.ManyToManyField(to='catalog.SubCategory', verbose_name='Equipment related')),
            ],
        ),
    ]
