# Generated by Django 3.1.2 on 2021-03-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0077_auto_20210322_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryequipment',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Ordering'),
        ),
    ]
