# Generated by Django 3.1.2 on 2021-03-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0078_categoryequipment_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryequipment',
            options={'ordering': ('order',), 'verbose_name': 'Category Equipment', 'verbose_name_plural': 'Categories Equipment'},
        ),
    ]
