# Generated by Django 3.1.2 on 2021-03-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0082_auto_20210329_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='identifier',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Identifier'),
        ),
    ]
