# Generated by Django 3.1.2 on 2021-04-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0084_workout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
