# Generated by Django 3.1.2 on 2021-04-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0085_block_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['order'], 'verbose_name': 'Workout', 'verbose_name_plural': 'Workouts'},
        ),
    ]
