# Generated by Django 3.1.2 on 2021-04-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0086_auto_20210416_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Workout name'),
        ),
    ]
