# Generated by Django 3.1.2 on 2020-10-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_remove_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Super Admin'), (2, 'Institution Manager'), (4, 'Strength Coach'), (3, 'Athlete')], default=3, verbose_name='Rol'),
        ),
    ]
