# Generated by Django 3.1.2 on 2020-10-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('regions', '0002_auto_20201015_1616'),
        ('security', '0004_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2020-01-20', verbose_name='Date Birthday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.PositiveSmallIntegerField(default=42, verbose_name='code country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'FEMALE'), (2, 'MALE'), (3, 'OTHER')], default=3, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team', verbose_name='Team asociated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='9861073003', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.region', verbose_name='Region user'),
        ),
    ]
