# Generated by Django 3.1.2 on 2020-10-15 18:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_auto_20201015_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
