# Generated by Django 3.1.2 on 2020-10-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_user_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'Super Admin'), (2, 'Institution Manager'), (3, 'Strength Coach'), (4, 'Athlete')], default=3, verbose_name='Rol'),
        ),
    ]
