# Generated by Django 3.1.2 on 2020-10-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Date Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='code country'),
        ),
    ]
