# Generated by Django 3.1.2 on 2020-10-19 01:17

import apps.security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_auto_20201019_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Date Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='code country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.security.models.path_and_rename, verbose_name='photo profile'),
        ),
    ]
