# Generated by Django 3.1.2 on 2020-10-20 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_institution'),
        ('security', '0009_auto_20201019_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.institution', verbose_name='institution'),
        ),
    ]
