# Generated by Django 3.1.2 on 2020-10-27 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_user_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_edited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='last user edit this user'),
        ),
    ]
