# Generated by Django 3.1.2 on 2020-10-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_user_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='heigth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='heigth user'),
        ),
        migrations.AddField(
            model_name='user',
            name='weigth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='weigth user'),
        ),
    ]
