# Generated by Django 3.1.2 on 2020-11-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20201029_1743'),
        ('security', '0013_remove_user_subscription_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ManyToManyField(blank=True, to='teams.Team', verbose_name='Team asociated'),
        ),
    ]
