# Generated by Django 3.1.2 on 2020-11-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0014_auto_20201105_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
    ]
