# Generated by Django 3.1.2 on 2020-11-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0015_remove_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_widget',
            field=models.BooleanField(default=False, verbose_name='email verified?'),
        ),
    ]
