# Generated by Django 3.1.2 on 2020-11-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0016_user_deleted_widget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
