# Generated by Django 3.1.2 on 2021-02-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0017_auto_20201118_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='FCM',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='maximum heart rate'),
        ),
        migrations.AddField(
            model_name='user',
            name='MAS',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Maximal Aerobic Speed'),
        ),
        migrations.AddField(
            model_name='user',
            name='MSS',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Maximal Sprinting Speed'),
        ),
    ]
