# Generated by Django 3.1.2 on 2021-02-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0018_auto_20210225_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FCM',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='maximum heart rate (bpm)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='MAS',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Maximal Aerobic Speed (km/h)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='MSS',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Maximal Sprinting Speed (km/h)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='heigth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='heigth user (m)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weigth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='weigth user (kg)'),
        ),
    ]
