# Generated by Django 3.1.2 on 2021-03-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0019_auto_20210225_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='languaje',
            field=models.IntegerField(choices=[(1, 'English'), (2, 'Spanish')], default=2, verbose_name='Languaje'),
        ),
        migrations.AddField(
            model_name='user',
            name='metric_system',
            field=models.IntegerField(choices=[(1, 'English'), (2, 'International')], default=2, verbose_name='System Metric'),
        ),
    ]
