# Generated by Django 3.1.2 on 2021-03-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0020_auto_20210305_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_type',
            field=models.IntegerField(choices=[(1, 'Facebook'), (2, 'Google'), (3, 'Apple'), (4, 'Default')], default=4, verbose_name='Social Login Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='token_social_login',
            field=models.TextField(blank=True, null=True),
        ),
    ]
