# Generated by Django 3.1.2 on 2021-03-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0021_auto_20210317_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='automatic_training',
            field=models.BooleanField(default=False, verbose_name='Training automatic enabled'),
        ),
    ]
