# Generated by Django 3.1.2 on 2020-10-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name team')),
                ('plan_active', models.BooleanField(default=False, verbose_name='has plan active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revanue', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='total revenue')),
                ('active', models.BooleanField(default=False, verbose_name='product active')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
    ]
