# Generated by Django 3.1.2 on 2020-10-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20201020_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='identifier_name',
            field=models.CharField(default='db_seleccionmexicanadefutbol', max_length=250, unique=True, verbose_name='Name team'),
            preserve_default=False,
        ),
    ]
