# Generated by Django 3.1.2 on 2020-10-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_institution_identifier_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='plan_active',
        ),
    ]
