# Generated by Django 3.1.2 on 2020-10-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_created_by_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='created_by_team',
            new_name='institution',
        ),
    ]
