# Generated by Django 3.1.2 on 2020-10-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20201022_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=True, verbose_name='institution active'),
        ),
    ]
