# Generated by Django 3.1.2 on 2020-10-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_team_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='revanue',
            new_name='revenue',
        ),
    ]
