# Generated by Django 3.1.2 on 2020-11-05 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0009_auto_20201029_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='athletes',
            field=models.ManyToManyField(blank=True, related_name='team_athletes', to=settings.AUTH_USER_MODEL, verbose_name='Athletes of team'),
        ),
        migrations.AddField(
            model_name='team',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='team_coaches', to=settings.AUTH_USER_MODEL, verbose_name='Coaches of team'),
        ),
        migrations.AddField(
            model_name='team',
            name='institution_managers',
            field=models.ManyToManyField(blank=True, related_name='team_institution_managers', to=settings.AUTH_USER_MODEL, verbose_name='Institution managers of team'),
        ),
    ]
