# Generated by Django 3.1.2 on 2020-11-05 17:58

import apps.teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20201105_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='22', upload_to=apps.teams.models.path_and_rename, verbose_name='image team'),
            preserve_default=False,
        ),
    ]
