# Generated by Django 3.1.2 on 2020-11-05 18:20

import apps.teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20201105_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.teams.models.path_and_rename, verbose_name='image team'),
        ),
    ]
