# Generated by Django 3.1.2 on 2021-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VariationHorizontal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Variation Horizontal')),
                ('change_exercises', models.BooleanField(default=True, verbose_name='Change Exercises')),
                ('change_reps', models.BooleanField(default=True, verbose_name='Change Reps')),
            ],
            options={
                'verbose_name': 'Variation Horizontal',
                'verbose_name_plural': 'Variations Horizontal',
            },
        ),
        migrations.CreateModel(
            name='VariationVertical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Variation Vertical')),
                ('intensity', models.IntegerField(blank=True, null=True, verbose_name='intensity')),
                ('volumen', models.CharField(blank=True, max_length=300, null=True, verbose_name='reps upper body')),
            ],
            options={
                'verbose_name': ' Variaton Vertical',
                'verbose_name_plural': 'Variations Vertical',
            },
        ),
    ]
