# Generated by Django 3.1.2 on 2021-03-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0010_categoryselectionniveluser_equip'),
        ('catalog', '0075_auto_20210310_1909'),
        ('help_coach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationvertical',
            name='volumen',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='volumen'),
        ),
        migrations.CreateModel(
            name='WeekVariationHorizontal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_horizontal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='help_coach.variationhorizontal', verbose_name=' Varition')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.week', verbose_name='Week')),
            ],
            options={
                'verbose_name': 'Variation Horizontal Week',
                'verbose_name_plural': 'Variations Horizontal Weeks',
            },
        ),
        migrations.CreateModel(
            name='VariationVerticalProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.program', verbose_name='Program')),
                ('variation_vertical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='help_coach.variationvertical', verbose_name='Related Varition')),
            ],
            options={
                'verbose_name': 'Variation Vertical Program',
                'verbose_name_plural': 'Variations Vertical Programs',
            },
        ),
        migrations.CreateModel(
            name='RegionsCategoryCoach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nivel', to='coach.categoryselectionniveluser', verbose_name='Related category_selection_nivel_user')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_regionscategorycoach', to='catalog.program', verbose_name='program')),
                ('regions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions_category_coach', to='catalog.subcategory', verbose_name='regions')),
            ],
            options={
                'verbose_name': 'Region Category',
                'verbose_name_plural': 'Regions Categories',
            },
        ),
    ]
