# Generated by Django 3.1.2 on 2021-03-18 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0075_auto_20210310_1909'),
        ('help_coach', '0003_auto_20210318_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionscategorycoach',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='variationverticalprogram',
            name='program',
        ),
        migrations.AddField(
            model_name='regionscategorycoach',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_regionscategorycoach', to='catalog.program', verbose_name='program'),
        ),
        migrations.AddField(
            model_name='variationverticalprogram',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.phase', verbose_name='Program'),
        ),
    ]
