# Generated by Django 3.1.2 on 2021-03-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0075_auto_20210310_1909'),
        ('help_coach', '0004_auto_20210318_0648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variationverticalprogram',
            options={'verbose_name': 'Variation Vertical Phase', 'verbose_name_plural': 'Variations Vertical Phase'},
        ),
        migrations.RemoveField(
            model_name='regionscategorycoach',
            name='program',
        ),
        migrations.AddField(
            model_name='regionscategorycoach',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phaseregionscategorycoach', to='catalog.phase', verbose_name='Phase'),
        ),
        migrations.AddField(
            model_name='weekvariationhorizontal',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Relation_phase', to='catalog.phase', verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='variationverticalprogram',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.phase', verbose_name='Phase'),
        ),
    ]
