# Generated by Django 3.1.2 on 2021-03-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0079_auto_20210323_0945'),
        ('help_coach', '0005_auto_20210318_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramWorkouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workouts_program', models.JSONField()),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Relation_program', to='catalog.program', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Program Workout',
                'verbose_name_plural': 'Program Workouts',
            },
        ),
    ]
