# Generated by Django 3.1.2 on 2021-04-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_coach', '0007_auto_20210405_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationverticalprogram',
            name='variation_vertical',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='help_coach.variationvertical', verbose_name='Related Varition'),
        ),
        migrations.AlterField(
            model_name='weekvariationhorizontal',
            name='variation_horizontal',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='help_coach.variationhorizontal', verbose_name=' Varition'),
        ),
    ]
