# Generated by Django 3.1.2 on 2021-04-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_coach', '0008_auto_20210413_0438'),
        ('help_coach', '0008_auto_20210406_1517'),
    ]

    operations = [
    ]
