# Generated by Django 3.1.2 on 2020-11-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201029_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwidget',
            name='order',
        ),
        migrations.AddField(
            model_name='userwidget',
            name='axis_x',
            field=models.IntegerField(default=0, verbose_name='Axis x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwidget',
            name='axis_y',
            field=models.IntegerField(default=0, verbose_name='Axis y'),
            preserve_default=False,
        ),
    ]
