# Generated by Django 3.1.2 on 2020-11-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20201105_1820'),
        ('dashboard', '0006_auto_20201120_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='team',
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ManyToManyField(blank=True, to='teams.Team', verbose_name='Teams event'),
        ),
    ]
