# Generated by Django 3.1.2 on 2020-12-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_eventposter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventposter',
            options={'verbose_name': 'Event Poster', 'verbose_name_plural': 'Events Poster'},
        ),
    ]
