# Generated by Django 3.1.2 on 2021-04-21 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210421_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='max',
            field=models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Maximun size'),
        ),
        migrations.AddField(
            model_name='widget',
            name='min',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='Minumun size'),
        ),
    ]
